name: Heroku waker

on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
    - name: Send signal
      run: curl -L https://f3c.herokuapp.com/
      
    - name: Delete workflow runs
      uses: MajorScruffy/delete-workflow-runs@main
      id: delete-workflow-runs
      with:
        repository: klever1988/F3com   # replace this with your own repository
        older-than-seconds: 86400                       # remove all workflow runs older than 1 day
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
